# Generated by Django 2.2.5 on 2019-12-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_commentblog_postblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TROUSERS', 'TROUSERS'), ('SHIRT', 'SHIRT'), ('SHOES', 'SHOES')], max_length=50),
        ),
    ]
