# Generated by Django 2.2.5 on 2019-12-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20191222_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TR', 'TROUSERS'), ('S', 'SHIRT'), ('SH', 'SHOES')], max_length=50),
        ),
    ]
